---
- name: install ntp
  hosts: all
  become_user: root
  become: true
  vars:
      timesync_ntp_provider: chrony
      timesync_ntp_servers:
          - hostname: <>
            iburst: true
  roles:
      - role: "ansible/roles/rhel-system-roles.timesync"
